markdown: rdiscount
pygments: true
permalink: /blog/:year/:month/:title
include: ['.htaccess']
exclude: ['node_modules', 'scss', 'Gruntfile.js', 'package.json', '*.sublime-project', '*.sublime-workspace', 'index-static.php', 'index-jekyll.html', 'index-handlebars.php', 'blog-src']
timezone: Europe/London

paginate: 8
paginate_path: /blog/page:num

# Vars
name: Zander Martineau
myname: Zander Martineau
email: zander@martineau.tv
socialusername: MrMartineau